package qtqml
type QJSEngine__Extension = int
const QJSEngine__TranslationExtension QJSEngine__Extension = 1
const QJSEngine__ConsoleExtension QJSEngine__Extension = 2
const QJSEngine__GarbageCollectionExtension QJSEngine__Extension = 4
const QJSEngine__AllExtensions QJSEngine__Extension = -1
type QJSValue__SpecialValue = int
const QJSValue__NullValue QJSValue__SpecialValue = 0
const QJSValue__UndefinedValue QJSValue__SpecialValue = 1
type QJSValue__ErrorType = int
const QJSValue__NoError QJSValue__ErrorType = 0
const QJSValue__GenericError QJSValue__ErrorType = 1
const QJSValue__EvalError QJSValue__ErrorType = 2
const QJSValue__RangeError QJSValue__ErrorType = 3
const QJSValue__ReferenceError QJSValue__ErrorType = 4
const QJSValue__SyntaxError QJSValue__ErrorType = 5
const QJSValue__TypeError QJSValue__ErrorType = 6
const QJSValue__URIError QJSValue__ErrorType = 7
type QQmlAbstractUrlInterceptor__DataType = int
const QQmlAbstractUrlInterceptor__QmlFile QQmlAbstractUrlInterceptor__DataType = 0
const QQmlAbstractUrlInterceptor__JavaScriptFile QQmlAbstractUrlInterceptor__DataType = 1
const QQmlAbstractUrlInterceptor__QmldirFile QQmlAbstractUrlInterceptor__DataType = 2
const QQmlAbstractUrlInterceptor__UrlString QQmlAbstractUrlInterceptor__DataType = 4096
type QQmlComponent__CompilationMode = int
const QQmlComponent__PreferSynchronous QQmlComponent__CompilationMode = 0
const QQmlComponent__Asynchronous QQmlComponent__CompilationMode = 1
type QQmlComponent__Status = int
const QQmlComponent__Null QQmlComponent__Status = 0
const QQmlComponent__Ready QQmlComponent__Status = 1
const QQmlComponent__Loading QQmlComponent__Status = 2
const QQmlComponent__Error QQmlComponent__Status = 3
type QQmlDebuggingEnabler__StartMode = int
const QQmlDebuggingEnabler__DoNotWaitForClient QQmlDebuggingEnabler__StartMode = 0
const QQmlDebuggingEnabler__WaitForClient QQmlDebuggingEnabler__StartMode = 1
type QQmlEngine__ObjectOwnership = int
const QQmlEngine__CppOwnership QQmlEngine__ObjectOwnership = 0
const QQmlEngine__JavaScriptOwnership QQmlEngine__ObjectOwnership = 1
type QQmlFile__Status = int
const QQmlFile__Null QQmlFile__Status = 0
const QQmlFile__Ready QQmlFile__Status = 1
const QQmlFile__Error QQmlFile__Status = 2
const QQmlFile__Loading QQmlFile__Status = 3
type QQmlImageProviderBase__ImageType = int
const QQmlImageProviderBase__Image QQmlImageProviderBase__ImageType = 0
const QQmlImageProviderBase__Pixmap QQmlImageProviderBase__ImageType = 1
const QQmlImageProviderBase__Texture QQmlImageProviderBase__ImageType = 2
const QQmlImageProviderBase__Invalid QQmlImageProviderBase__ImageType = 3
const QQmlImageProviderBase__ImageResponse QQmlImageProviderBase__ImageType = 4
type QQmlImageProviderBase__Flag = int
const QQmlImageProviderBase__ForceAsynchronousImageLoading QQmlImageProviderBase__Flag = 1
type QQmlIncubator__IncubationMode = int
const QQmlIncubator__Asynchronous QQmlIncubator__IncubationMode = 0
const QQmlIncubator__AsynchronousIfNested QQmlIncubator__IncubationMode = 1
const QQmlIncubator__Synchronous QQmlIncubator__IncubationMode = 2
type QQmlIncubator__Status = int
const QQmlIncubator__Null QQmlIncubator__Status = 0
const QQmlIncubator__Ready QQmlIncubator__Status = 1
const QQmlIncubator__Loading QQmlIncubator__Status = 2
const QQmlIncubator__Error QQmlIncubator__Status = 3
type QQmlProperty__PropertyTypeCategory = int
const QQmlProperty__InvalidCategory QQmlProperty__PropertyTypeCategory = 0
const QQmlProperty__List QQmlProperty__PropertyTypeCategory = 1
const QQmlProperty__Object QQmlProperty__PropertyTypeCategory = 2
const QQmlProperty__Normal QQmlProperty__PropertyTypeCategory = 3
type QQmlProperty__Type = int
const QQmlProperty__Invalid QQmlProperty__Type = 0
const QQmlProperty__Property QQmlProperty__Type = 1
const QQmlProperty__SignalProperty QQmlProperty__Type = 2
